services:
  qa-platform-api:
    build:
      context: "."
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5050:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - qa-platform-db
    networks:
      - qa-platform-network-prod

  qa-platform-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: qa-platform-db
    volumes:
      - qa-platform-volume-prod:/var/lib/postgresql/data
    networks:
      - qa-platform-network-prod

volumes:
  qa-platform-volume-prod:

networks:
  qa-platform-network-prod:
    driver: bridge
