services:
  qa-platform-db:
    image: postgres:latest
    container_name: qa-platform-db-dev
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: qa-platform-db
    ports:
      - "5432:5432"
    volumes:
      - qa-platform-volume-dev:/var/lib/postgresql/data
    networks:
      - qa-platform-network-dev

  qa-platform-db-admin:
    image: dpage/pgadmin4
    container_name: qa-platform-db-admin-dev
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.com
      PGADMIN_DEFAULT_PASSWORD: devpassword
    ports:
      - "8081:80"
    depends_on:
      - qa-platform-db
    networks:
      - qa-platform-network-dev

volumes:
  qa-platform-volume-dev:

networks:
  qa-platform-network-dev:
    driver: bridge
