services:
  client:
    image: registry.gitlab.com/martelleur1/qa-platform-deployment/qa-client:latest
    restart: always
    ports:
      - "3030:80"
    networks:
      - qa-platform-network-prod

  qa-platform-api:
    image: registry.gitlab.com/martelleur1/qa-platform-deployment/qa-api:latest
    restart: always
    ports:
      - "5050:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - qa-platform-db
    networks:
      - qa-platform-network-prod

  qa-platform-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin-qa-platform
      POSTGRES_PASSWORD: iyDQpkdFv26vcfWtrvsFuy4VXs6tgDbpfVUv5E
      POSTGRES_DB: qa-platform-db
    volumes:
      - qa-platform-volume-prod:/var/lib/postgresql/data
    networks:
      - qa-platform-network-prod

volumes:
  qa-platform-volume-prod:

networks:
  qa-platform-network-prod:
    driver: bridge
