services:
  qa-platform-api:
    build:
      context: "."
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5050:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Testing
    depends_on:
      qa-platform-db:
        condition: service_healthy
    networks:
      - qa-platform-network-test

  qa-platform-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: qa-platform-db
    ports:
      - "5433:5432"
    volumes:
      - qa-platform-volume-test:/var/lib/postgresql/data
    networks:
      - qa-platform-network-test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d qa-platform-db"]
      interval: 5s
      timeout: 3s
      retries: 5

  qa-platform-db-admin:
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.com
      PGADMIN_DEFAULT_PASSWORD: devpassword
    ports:
      - "8081:80"
    depends_on:
      - qa-platform-db
    networks:
      - qa-platform-network-test

volumes:
  qa-platform-volume-test:

networks:
  qa-platform-network-test:
    driver: bridge
