name: QA Platform build and test workflow

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  setup-db:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Start Database with Docker Compose
      run: docker compose -f docker-compose-test.yml up -d qa-platform-db

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-db

    steps:
    - uses: actions/checkout@v4

    - name: Start API Container
      run: docker compose -f docker-compose-test.yml up -d qa-platform-api

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependenciesTEST
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run All Tests
      env:
        TEST_ENV: "GITHUB_ACTIONS"
      run: dotnet test --no-build --verbosity normal

    - name: Stop and clean up containers
      run: docker compose -f docker-compose-test.yml down
